from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

new_cart=r'''<main id="cartPage" class="page cart-v3"><div class="cart-page-head"><div><span class="cart-eyebrow">MauriOne</span><h1 id="cartPageTitle">السلة والطلبات</h1><p id="cartPageSubtitle">تسوق الآن وتابع طلباتك بعد التأكيد من نفس المكان.</p></div><button class="cart-continue" onclick="openStore('home','navHome')">متابعة التسوق</button></div><div class="cart-tabs"><button id="cartTabCart" class="active" onclick="setCartView('cart')"><span id="cartSectionTitle">سلة الشراء</span><b id="cartItemsCount">0</b></button><button id="cartTabOrders" onclick="setCartView('orders')"><span id="ordersSectionTitle">طلباتي</span><b id="ordersCount">0</b></button></div><section id="cartPanel" class="cart-panel active"><div id="cartList" class="cart-items-v3"></div><div class="cart-summary-v3" id="cartSummary"><div class="cart-summary-head"><div><small>ملخص السلة</small><strong>الإجمالي قبل التأكيد</strong></div><span aria-hidden="true">🛍</span></div><div class="cart-summary-row"><span id="cartSubtotalLabel">إجمالي المنتجات</span><strong id="cartSubtotal">0 MRU</strong></div><div id="deliveryAtCheckoutText" class="cart-delivery-hint">تُحسب رسوم التوصيل بعد إدخال المدينة.</div><button class="cart-checkout" id="checkoutBtn" onclick="checkout()">إتمام الطلب</button></div></section><section id="ordersPanel" class="cart-panel"><div class="orders-panel-head"><div><small>متابعة الطلبات</small><h2>طلباتك من MauriOne</h2></div><span>تحديث مباشر للحالة</span></div><div id="myOrdersList" class="my-orders"></div></section></main>'''

pattern=re.compile(r'<main id="cartPage" class="page">.*?</main>\s*<main id="accountPage" class="page">',re.S)
s,n=pattern.subn(new_cart+'\n<main id="accountPage" class="page">',s,count=1)
if n!=1:
    raise SystemExit(f'cart markup anchor not found or ambiguous: {n}')

old_render=re.compile(r"function renderCart\(\)\{.*?checkoutBtn\.disabled=!rows\.length\}",re.S)
new_render=r'''function renderCart(){const rows=cartRows(),count=document.getElementById('cartItemsCount'),summary=document.getElementById('cartSummary');if(count)count.textContent=String(rows.reduce((s,x)=>s+Number(x.qty||0),0));cartList.innerHTML=rows.length?rows.map(({p,qty})=>{const img=Array.isArray(p.images)&&p.images[0]?String(p.images[0]):'';return `<article class="cart-item-v3"><button class="cart-item-image" onclick="openProduct('${esc(p.id)}')" aria-label="فتح ${esc(p.name)}">${img?`<img src="${esc(img)}" alt="${esc(p.name)}">`:'<div class="cart-item-noimg">M</div>'}</button><div class="cart-item-content"><div class="cart-item-main"><div><small>${esc(displayCategory(p.category||''))}</small><strong onclick="openProduct('${esc(p.id)}')">${esc(p.name)}</strong>${p.meta?`<p>${esc(p.meta)}</p>`:''}</div><button class="cart-remove-v3" onclick="removeCart('${esc(p.id)}')" aria-label="حذف">×</button></div><div class="cart-item-bottom"><div class="cart-qty-v3"><button onclick="changeQty('${esc(p.id)}',-1)" aria-label="إنقاص">−</button><b>${qty}</b><button onclick="changeQty('${esc(p.id)}',1)" aria-label="زيادة">+</button></div><div class="cart-line-price"><small>${Number(p.price||0).toLocaleString()} MRU × ${qty}</small><strong>${money(Number(p.price||0)*qty)}</strong></div></div></div></article>`}).join(''):`<div class="cart-empty-v3"><div class="cart-empty-icon"><svg viewBox="0 0 32 32"><path d="M5 7h3l2.5 13h12.8l2.8-9.5H9"/><circle cx="13" cy="25" r="1.5"/><circle cx="23" cy="25" r="1.5"/></svg></div><h3>سلتك فارغة</h3><p>اختر المنتجات التي تريدها وسنحتفظ بها هنا حتى تكمل الطلب.</p><button onclick="openStore('home','navHome')">ابدأ التسوق</button></div>`;cartSubtotal.textContent=money(cartSubtotalValue());checkoutBtn.disabled=!rows.length;if(summary)summary.style.display=rows.length?'block':'none'}'''
s,n=old_render.subn(new_render,s,count=1)
if n!=1:
    raise SystemExit(f'renderCart anchor not found or ambiguous: {n}')

s=s.replace("function renderMyOrders(){if(!orderHistory.length){","function renderMyOrders(){const oc=document.getElementById('ordersCount');if(oc)oc.textContent=String(orderHistory.length);if(!orderHistory.length){",1)

anchor="window.openStore=(id,nav)=>{"
if anchor not in s:
    raise SystemExit('openStore anchor missing')
view_fn=r'''window.setCartView=view=>{const cart=view!=='orders',cp=document.getElementById('cartPanel'),op=document.getElementById('ordersPanel'),ct=document.getElementById('cartTabCart'),ot=document.getElementById('cartTabOrders');cp?.classList.toggle('active',cart);op?.classList.toggle('active',!cart);ct?.classList.toggle('active',cart);ot?.classList.toggle('active',!cart);if(!cart){renderMyOrders();connectTracking()}window.scrollTo({top:0,behavior:'smooth'})};
'''
s=s.replace(anchor,view_fn+anchor,1)
s=s.replace("if(id==='cartPage'){renderCart();renderMyOrders();connectTracking()}","if(id==='cartPage'){renderCart();renderMyOrders();connectTracking();setCartView('cart')}",1)

css=r'''
/* MauriOne cart v9 */
.cart-v3{min-height:calc(100vh - 64px);background:#f7f7f8;padding:0 0 28px}
.cart-page-head{padding:22px 14px 12px;display:flex;align-items:flex-start;justify-content:space-between;gap:14px;background:#fff}
.cart-page-head .cart-eyebrow{display:block;color:var(--gold);font-size:9px;font-weight:700;margin-bottom:3px}.cart-page-head h1{font-size:25px;line-height:1.25}.cart-page-head p{margin-top:4px;color:var(--muted);font-size:9.5px;line-height:1.6;max-width:340px}.cart-continue{flex:0 0 auto;border:1px solid var(--line);background:#fff;border-radius:12px;padding:9px 11px;font-size:9px;color:#555}
.cart-tabs{position:sticky;top:64px;z-index:35;display:grid;grid-template-columns:1fr 1fr;gap:5px;margin:0;padding:8px 12px;background:rgba(247,247,248,.96);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}.cart-tabs button{height:43px;border:0;border-radius:13px;background:#ececef;color:#777;font-size:11px;font-weight:600;display:flex;align-items:center;justify-content:center;gap:7px}.cart-tabs button b{min-width:20px;height:20px;padding:0 5px;border-radius:20px;background:rgba(255,255,255,.7);display:grid;place-items:center;font-size:8px}.cart-tabs button.active{background:var(--navy);color:#fff}.cart-tabs button.active b{background:rgba(255,255,255,.14);color:#fff}
.cart-panel{display:none;padding:4px 12px 20px}.cart-panel.active{display:block}.cart-items-v3{display:grid;gap:9px}
.cart-item-v3{display:grid;grid-template-columns:88px 1fr;gap:12px;background:#fff;border:1px solid #ececef;border-radius:19px;padding:10px;box-shadow:0 4px 16px rgba(7,21,34,.025)}.cart-item-image{width:88px;height:88px;border:0;border-radius:14px;background:#f8f8fa;overflow:hidden;padding:0}.cart-item-image img{width:100%;height:100%;object-fit:contain;background:#fff}.cart-item-noimg{height:100%;display:grid;place-items:center;font-size:25px;font-weight:700;color:var(--gold)}.cart-item-content{min-width:0}.cart-item-main{display:flex;justify-content:space-between;gap:8px}.cart-item-main small{display:block;color:var(--muted);font-size:8px;margin-bottom:2px}.cart-item-main strong{display:block;font-size:12px;line-height:1.35;cursor:pointer}.cart-item-main p{color:var(--muted);font-size:8.5px;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:210px}.cart-remove-v3{width:28px;height:28px;flex:0 0 28px;border:0;border-radius:9px;background:#fff2f2;color:#b32929;font-size:18px}.cart-item-bottom{margin-top:11px;display:flex;align-items:end;justify-content:space-between;gap:10px}.cart-qty-v3{display:flex;align-items:center;gap:4px;border:1px solid var(--line);border-radius:10px;padding:3px;background:#fafafa;direction:ltr}.cart-qty-v3 button{width:27px;height:27px;border:0;border-radius:8px;background:#fff;font-size:16px}.cart-qty-v3 b{min-width:24px;text-align:center;font-size:11px}.cart-line-price{text-align:left;direction:ltr}.cart-line-price small{display:block;color:var(--muted);font-size:7.5px}.cart-line-price strong{display:block;margin-top:2px;font-size:12px}
.cart-summary-v3{margin-top:10px;background:#fff;border:1px solid #ececef;border-radius:20px;padding:15px;box-shadow:0 5px 20px rgba(7,21,34,.03)}.cart-summary-head{display:flex;align-items:center;justify-content:space-between;padding-bottom:11px;border-bottom:1px solid var(--line)}.cart-summary-head small{display:block;color:var(--muted);font-size:8px}.cart-summary-head strong{font-size:13px}.cart-summary-head>span{font-size:22px}.cart-summary-row{display:flex;justify-content:space-between;align-items:center;padding:13px 0 5px;font-size:11px}.cart-summary-row strong{font-size:15px;direction:ltr}.cart-delivery-hint{font-size:8.5px;color:var(--muted);margin:3px 0 12px}.cart-checkout{width:100%;min-height:49px;border:0;border-radius:13px;background:linear-gradient(135deg,#071522,#0e304e);color:#fff;font-size:13px;font-weight:700;box-shadow:0 8px 20px rgba(7,21,34,.14)}.cart-checkout:disabled{opacity:.4;box-shadow:none}
.cart-empty-v3{background:#fff;border:1px solid #ececef;border-radius:20px;padding:34px 20px;text-align:center}.cart-empty-icon{width:62px;height:62px;margin:0 auto 12px;border-radius:20px;background:#f7f7f8;display:grid;place-items:center}.cart-empty-icon svg{width:31px;height:31px;fill:none;stroke:var(--navy);stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}.cart-empty-v3 h3{font-size:17px}.cart-empty-v3 p{max-width:290px;margin:6px auto 14px;color:var(--muted);font-size:9.5px;line-height:1.7}.cart-empty-v3 button{border:0;border-radius:11px;background:var(--navy);color:#fff;padding:10px 18px;font-size:10px}
.orders-panel-head{display:flex;justify-content:space-between;align-items:end;gap:12px;padding:10px 2px 12px}.orders-panel-head small{display:block;color:var(--gold);font-size:8px}.orders-panel-head h2{font-size:18px}.orders-panel-head>span{font-size:8px;color:var(--muted)}.cart-v3 .my-orders{padding:0}.cart-v3 .customer-order{border-radius:19px;padding:13px;margin-bottom:9px;box-shadow:0 4px 16px rgba(7,21,34,.025)}.cart-v3 .customer-order-item{grid-template-columns:48px 1fr}.cart-v3 .customer-order-item img,.cart-v3 .customer-order-item .no-img{width:48px;height:48px}.cart-v3 .track{margin-top:10px;padding-top:10px}.cart-v3 .order-info{margin-top:9px}.cart-v3 .order-info div{padding:8px}.cart-v3 .order-total{margin-top:9px;padding-top:8px}
@media(max-width:390px){.cart-page-head{padding:18px 11px 10px}.cart-page-head h1{font-size:22px}.cart-continue{padding:8px 9px}.cart-tabs{padding:7px 10px}.cart-panel{padding-left:10px;padding-right:10px}.cart-item-v3{grid-template-columns:78px 1fr;padding:9px}.cart-item-image{width:78px;height:78px}.cart-item-main p{max-width:170px}}
'''
if '/* MauriOne cart v9 */' not in s:
    s=s.replace('</style>',css+'\n</style>',1)

p.write_text(s,encoding='utf-8')
